language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly

before_install:
  # Install TeX and Qt5 to build plots for documentation
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install basictex; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq x11-apps libxt6 libxrender1 libxext6 libgl1-mesa-glx qtbase5-dev qtdeclarative5-dev; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export GKSwstype=svg; fi

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("NeuralVerification"; coverage=true)'

# After successful build submit coverage report and deploy updated documentation
# But limit deployment to the linux worker so this is done only once.
after_success:
  # Install required packages for coverage and documentation
  - julia --project -e 'import Pkg; Pkg.add("Coverage");'
  - julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("DocumenterTools");'
#  - julia --project -e 'import Pkg; Pkg.add("Plots");'
#  - julia --project -e 'import Pkg; Pkg.add("LaTeXStrings")'

  # Submit test coverage report
  - julia --project -e 'using Coverage; Coveralls.submit(Coveralls.process_folder())'

  # Build and deploy documentation
  - julia --project ./docs/make.jl
